[package]
name = "shrek_lang_rust"
version = "0.1.0"
authors = ["Scott <Scottz0r@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
